#!/bin/sh

# ipacm   init.d script to start the data-ipa Software's ipacm daemon

set -e

case "$1" in
  start)
        echo -n "Starting ipacm: "
        start-stop-daemon -S -b -a ipacm
        echo "done"
        ;;
  stop)
        echo -n "Stopping ipacm: "
        start-stop-daemon -K -n ipacm
        echo "done"
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage ipacm { start | stop | restart}" >&2
        exit 1
        ;;
esac

exit 0
